version: 2

sources:
    - name: staging
     database: warm-ring-374916
     schema: dtc_dez_ny_taxi

     tables:
      - name: rides_green
      - name: rides_yellow
      - name: rides_fhv